### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tomzaku** [dudiharush/single-spa-react-typescript-app#1]
How to implement this repo to single-spa ?

**Comment by tomzaku** [comment]
https://gitlab.com/TheMcMurder/single-spa-portal-example

**Comment by dudiharush** [comment]
Just change the code in index.tsx to use multiple apps. The registerApplication function should get an activity function, which is where you should implement the routing logic to your apps.

Read more about the activity function here:
[https://github.com/CanopyTax/single-spa.js.org/blob/master/docs/single-spa-config.md](url)
